
				[package]
				name = "node-template-runtime-wasm"
				version = "1.0.0"
				edition = "2018"

				[lib]
				name = "node_template_runtime"
				crate-type = ["cdylib"]

				[dependencies]
				wasm_project = { package = "node-template-runtime", path = "/home/hskang9/standard-substrate/runtime", default-features = false, features = [  ] }
			